# Generated by Django 5.2.17 on 2026-09-29 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('client_name', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('web', 'Web'), ('saas', 'SaaS'), ('ai', 'AI'), ('mobile', 'Mobile'), ('enterprise', 'Enterprise')], default='web', max_length=20)),
                ('short_description', models.CharField(max_length=255)),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('architecture', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='case_studies/')),
                ('featured', models.BooleanField(default=False)),
                ('is_sample_data', models.BooleanField(default=False, help_text='Tick for demo content that is not a real client project.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'case studies',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('project_type', models.CharField(choices=[('web', 'Web application'), ('mobile', 'Mobile app'), ('saas', 'SaaS product'), ('ai', 'AI / Data'), ('enterprise', 'Enterprise software'), ('automation', 'Automation'), ('other', 'Something else')], max_length=20)),
                ('budget', models.CharField(choices=[('lt5k', 'Under $5k'), ('5k-15k', '$5k – $15k'), ('15k-50k', '$15k – $50k'), ('50k+', '$50k+'), ('unsure', 'Not sure yet')], max_length=20)),
                ('timeline', models.CharField(choices=[('asap', 'As soon as possible'), ('1-3m', '1–3 months'), ('3-6m', '3–6 months'), ('flexible', 'Flexible')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='new', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'contact inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('challenge', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='industries/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('ai', 'AI & Data'), ('devops', 'DevOps & Cloud')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Short glyph or initials shown on the card.', max_length=8)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'technologies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='case_studies/gallery/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.casestudy')),
            ],
        ),
        migrations.AddField(
            model_name='casestudy',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='core.industry'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Short glyph such as </> or {}.', max_length=8)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(blank=True, related_name='services', to='core.technology')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='casestudy',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='case_studies', to='core.technology'),
        ),
    ]
