# Generated by Django 5.2.17 on 2026-09-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional. A default illustration is used if empty.', upload_to='services/'),
        ),
    ]
