# Generated by Django 5.2.17 on 2026-10-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceQuickEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=150)),
                ('contact_info', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quick Service Enquiry',
                'verbose_name_plural': 'Quick Service Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
