# Generated by Django 5.2.17 on 2026-10-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicequickenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. Co-Founder & CTO, Principal Systems Architect', max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Short engineering / leadership overview')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('is_founder', models.BooleanField(default=False, help_text='Check if member is one of the 2 Co-Founders')),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated e.g. Python, Rust, Cloud, AI', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display priority (lower numbers appear first)')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', '-is_founder', 'id'],
            },
        ),
    ]
